### ISSUE TITLE
Allow Date object arguments

### ISSUE THREAD

**Issue by brettz9** [janrg/MeeusSunMoon#4]
While Moment and Moment Timezone are dependencies anyways, I think it would still be convenient if the API could detect for conversion normal JavaScript Date objects (if not timestamp numbers and date strings) where Moment objects are expected.

**Comment by janrg** [comment]
I'm not convinced that this would be a good idea due to the inherent issues that JavaScript Date objects have with timezones. If you want to make use of the Date object's best-guess date parsing, I would suggest then generating a moment object with explicit timezone information from that and passing that to MSM.
